dist: trusty
sudo: false
language: c++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
before_install:
  - bash install_deps.sh
  - export CC=gcc-6
  - export CXX=g++-6
  - export PATH="$HOME/deps/cmake/bin":"$PATH"
cache:
  directories:
    - $HOME/deps
script:
  - mkdir build && cd build && cmake -DBUILD_SINGLE_HEADER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror" .. && make -j2
